name: maifs
channels:
  - defaults
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - ipython==8.17.2
    - jax==0.4.13
    - jaxlib==0.4.13
    - jax_cfd[complete]
    - moviepy==1.0.3
    - numpy==1.24.3
    - setuptools==63.4.1
    - xarray==2022.9.0
    - ffmpeg-python